threadsafe: true
runtime: python27
default_expiration: "5m"
api_version: 1

handlers:

- url: /
  static_files: static/index.html
  upload: static/
  secure: always
  
- url: /studio
  static_files: static/studio.html
  upload: static/
  secure: always
  
- url: /recorder
  static_files: static/recorder.html
  upload: static/
  secure: always
  
- url: /profile
  static_files: static/userprofile.html
  upload: static/
  secure: always

- url: /moderate
  static_files: static/admin.html
  upload: static/
  secure: always

- url: /subtest
  static_files: static/subtest.html
  upload: static/
  secure: always

- url: /test
  static_files: static/test.html
  upload: static/
  secure: always
  
# - url: /static/jsons
  # static_dir: static/jsons
# 
# - url: /static/templates
  # static_dir: static/templates
# 
# - url: /dist/css
  # static_dir: dist/css
# 
# - url: /dist/js
  # static_dir: dist/js
# 
# - url: /dist/fonts
  # static_dir: dist/fonts  
# 
# - url: /static
  # static_dir: static

- url: /static
  static_dir: static
  secure: always


# - url: /static/js/libraries
  # static_dir: static/js/libraries

- url: /robots.txt
  static_files: siteconfig/robots.txt
  upload: siteconfig/robots.txt
  secure: always

- url: /abc.srt
  static_files: static/subs/abc.srt
  upload: static/subs
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "X-Requested-With, Content-Type"

- url: /.*
  script: start.application
  secure: always

libraries:

- name: jinja2
  version: latest

